In [11]:
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
print(tf.__version__)

2.3.0-rc2


In [12]:
model = tf.keras.models.load_model('con2_300.h5')
print("model successfully loaded")

model successfully loaded


In [36]:
model.layers

In [44]:
import json
import h5py
model_h5 = h5py.File('con2_300.h5','r')
model_config = model_h5["/"].attrs["model_config"]
config_dict = json.loads(model_config)
print(model_config)
print(config_dict)

b'{"class_name": "Sequential", "config": {"name": "sequential_2", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 300, 300, 3], "dtype": "float32", "sparse": false, "ragged": false, "name": "rescaling_4_input"}}, {"class_name": "Rescaling", "config": {"name": "rescaling_4", "trainable": true, "batch_input_shape": [null, 300, 300, 3], "dtype": "float32", "scale": 0.00392156862745098, "offset": 0.0}}, {"class_name": "Conv2D", "config": {"name": "conv2d_6", "trainable": true, "dtype": "float32", "filters": 64, "kernel_size": [3, 3], "strides": [1, 1], "padding": "same", "data_format": "channels_last", "dilation_rate": [1, 1], "groups": 1, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class

In [56]:
for l in model.variables:
    print(l.name)
    if(l.name=="conv2d_6/kernel:0"):
        tenL=l
    if(l.name=="conv2d_6/bias:0"):
        tenLb=l
    if(l.name=="conv2d_7/kernel:0"):
        tenL2=l
    if(l.name=="conv2d_7/bias:0"):
        tenLb2=l
    if(l.name=="dense_2/kernel:0"):
        tenLb3k=l
        #print("tenLb3k",tenLb3k)
    if(l.name=="dense_2/bias:0"):
        tenLb3b=l
#tenLb3k2, tenLb3k1= tf.split(tenLb3k,[37*75*128,38*75*128], axis=0)
one, temp = tf.split(tenLb3k,[25*75*128,50*75*128], axis=0)
two, three = tf.split(temp,[25*75*128,25*75*128], axis=0)

conv2d_6/kernel:0
conv2d_6/bias:0
conv2d_7/kernel:0
conv2d_7/bias:0
dense_2/kernel:0
dense_2/bias:0


In [14]:
import time
sunflower_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/592px-Red_sunflower.jpg"
sunflower_path = tf.keras.utils.get_file('Red_sunflower', origin=sunflower_url)
start_time = time.time()
img = tf.keras.preprocessing.image.load_img(
    sunflower_path , target_size=(300, 300))
img_array = tf.keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) # Create a batch
start_time = time.time()
predictions = model.predict(img_array)
print(predictions)
print("--- %s seconds ---" % (time.time() - start_time))

[[-1.5646616  -1.8227329   0.6618474  -0.3915253   0.43304604]]
--- 0.26999831199645996 seconds ---


In [15]:
c=tf.constant(([0.00392156862745098]))
img_array=tf.math.multiply(
    img_array, c, name=None
)

In [19]:
conv1=tf.keras.backend.conv2d(
    img_array, tenL, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,1)
)
bias1=tf.keras.backend.bias_add(conv1, tenLb)
relu1=tf.keras.backend.relu(
    bias1, alpha=0.0, max_value=None, threshold=0
)
pool1=tf.keras.backend.pool2d(relu1, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')

conv2=tf.keras.backend.conv2d(
    pool1, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,1)
)
bias2=tf.keras.backend.bias_add(conv2, tenLb2)
relu2=tf.keras.backend.relu(bias2, alpha=0.0, max_value=None, threshold=0)
pool2=tf.keras.backend.pool2d(relu2, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
flatten=tf.keras.backend.batch_flatten(pool2)
dense1=tf.keras.backend.dot(flatten,tenLb3k)
dbias1=tf.keras.backend.bias_add(dense1,tenLb3b)

In [45]:
sf0, sf1= tf.split(img_array,[108,192], axis=1)
temp1, temp2= tf.split(img_array,[92,208], axis=1)
mid, temp3= tf.split(temp2,[116,92], axis=1)
ss0, ss1= tf.split(img_array,[192,108], axis=1)

In [49]:
sf0

<tf.Tensor: shape=(1, 108, 300, 3), dtype=float32, numpy=
array([[[[0.5803922 , 0.7294118 , 0.97647065],
         [0.6       , 0.7490196 , 0.9960785 ],
         [0.6039216 , 0.75294125, 1.        ],
         ...,
         [0.37647063, 0.32941177, 0.38431376],
         [0.23529413, 0.10588236, 0.17254902],
         [0.2627451 , 0.09019608, 0.15686275]],

        [[0.6       , 0.7490196 , 0.9960785 ],
         [0.59607846, 0.74509805, 0.9921569 ],
         [0.5921569 , 0.7411765 , 0.98823535],
         ...,
         [0.4156863 , 0.5058824 , 0.48235297],
         [0.69411767, 0.7411765 , 0.7254902 ],
         [0.13333334, 0.16078432, 0.13333334]],

        [[0.6039216 , 0.75294125, 1.        ],
         [0.60784316, 0.7568628 , 1.        ],
         [0.60784316, 0.7490196 , 0.9921569 ],
         ...,
         [0.1137255 , 0.29411766, 0.19215688],
         [0.21960786, 0.40000004, 0.29803923],
         [0.08627451, 0.25882354, 0.15294118]],

        ...,

        [[0.24705884, 0.29411766, 

In [11]:
xx=tf.keras.backend.conv2d(
    img_array, 0, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)
xx=tf.keras.backend.bias_add(xx, tenLb)
xx=tf.keras.backend.relu(
    xx, alpha=0.0, max_value=None, threshold=0
)
xx=tf.keras.backend.pool2d(xx, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
############################################

xx=tf.keras.backend.conv2d(
    xx, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)
xx=tf.keras.backend.bias_add(xx, tenLb2)
xx=tf.keras.backend.relu(xx, alpha=0.0, max_value=None, threshold=0)
xx=tf.keras.backend.pool2d(xx, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
xx=tf.keras.backend.batch_flatten(xx)
xx=tf.keras.backend.dot(xx,tenLb3k)
xx=tf.keras.backend.bias_add(xx,tenLb3b)

# xx=tf.keras.backend.bias_add(xx, tenLb)
# xx=tf.keras.backend.relu(
#     xx, alpha=0.0, max_value=None, threshold=0
# )
sf0, sf1= tf.split(img_array,[152,148], axis=1)
ss0, ss1= tf.split(img_array,[144,156], axis=1)

In [35]:
pool2

<tf.Tensor: shape=(1, 75, 75, 128), dtype=float32, numpy=
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ...,

In [50]:
c1_1=tf.keras.backend.conv2d(
    sf0,tenL, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,1)
)
b1_1=tf.keras.backend.bias_add(c1_1, tenLb)
r1_1=tf.keras.backend.relu(
    b1_1, alpha=0.0, max_value=None, threshold=0
)
p1_1=tf.keras.backend.pool2d(r1_1, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
c2_1=tf.keras.backend.conv2d(
    p1_1, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,1)
)
b2_1=tf.keras.backend.bias_add(c2_1, tenLb2)
r2_1=tf.keras.backend.relu(b2_1, alpha=0.0, max_value=None, threshold=0)
p2_1=tf.keras.backend.pool2d(r2_1, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')

In [52]:
c1_2=tf.keras.backend.conv2d(
    mid,tenL, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,1)
)
b1_2=tf.keras.backend.bias_add(c1_2, tenLb)
r1_2=tf.keras.backend.relu(
    b1_2, alpha=0.0, max_value=None, threshold=0
)
p1_2=tf.keras.backend.pool2d(r1_2, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
c2_2=tf.keras.backend.conv2d(
    p1_2, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,1)
)
b2_2=tf.keras.backend.bias_add(c2_2, tenLb2)
r2_2=tf.keras.backend.relu(b2_2, alpha=0.0, max_value=None, threshold=0)
p2_2=tf.keras.backend.pool2d(r2_2, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')

In [54]:
c1_3=tf.keras.backend.conv2d(
    ss1,tenL, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,1)
)
b1_3=tf.keras.backend.bias_add(c1_3, tenLb)
r1_3=tf.keras.backend.relu(
    b1_3, alpha=0.0, max_value=None, threshold=0
)
p1_3=tf.keras.backend.pool2d(r1_3, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
c2_3=tf.keras.backend.conv2d(
    p1_3, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,1)
)
b2_3=tf.keras.backend.bias_add(c2_3, tenLb2)
r2_3=tf.keras.backend.relu(b2_3, alpha=0.0, max_value=None, threshold=0)
p2_3=tf.keras.backend.pool2d(r2_3, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')

In [60]:
first,sf00= tf.split(p2_1,[25,2], axis=1)
first=tf.keras.backend.batch_flatten(first)
first=tf.keras.backend.dot(first,one)

temp1,temp2= tf.split(p2_2,[2,27], axis=1)
second,temp3= tf.split(temp2,[25,2], axis=1)
second=tf.keras.backend.batch_flatten(second)
second=tf.keras.backend.dot(second,two)

temp4,third= tf.split(p2_3,[2,25], axis=1)
third=tf.keras.backend.batch_flatten(third)
third=tf.keras.backend.dot(third,three)

In [16]:
xx1=tf.keras.backend.conv2d(
    sf0,tenL, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)
xx1=tf.keras.backend.bias_add(xx1, tenLb)
xx1=tf.keras.backend.relu(
    xx1, alpha=0.0, max_value=None, threshold=0
)
xx1=tf.keras.backend.pool2d(xx1, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
#---------------------------------------------------------
xx1=tf.keras.backend.conv2d(
    xx1, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)

xx1=tf.keras.backend.bias_add(xx1, tenLb2)
xx1=tf.keras.backend.relu(xx1, alpha=0.0, max_value=None, threshold=0)
xx1=tf.keras.backend.pool2d(xx1, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')

xx1,sf00= tf.split(xx1,[37,1], axis=1)
xx1=tf.keras.backend.batch_flatten(xx1)
xx1=tf.keras.backend.dot(xx1,tenLb3k2)

# xx1=tf.keras.backend.bias_add(xx1,tenLb)
# xx1=tf.keras.backend.relu(
#     xx1, alpha=0.0, max_value=None, threshold=0
# )
#######################################################################################
xx2=tf.keras.backend.conv2d(
    ss1,tenL, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)
xx2=tf.keras.backend.bias_add(xx2,tenLb)
xx2=tf.keras.backend.relu(
    xx2, alpha=0.0, max_value=None, threshold=0
)
xx2=tf.keras.backend.pool2d(xx2, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
#----------------------------------------------
xx2=tf.keras.backend.conv2d(
    xx2, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)

xx2=tf.keras.backend.bias_add(xx2, tenLb2)
xx2=tf.keras.backend.relu(xx2, alpha=0.0, max_value=None, threshold=0)
#ss00, xx2= tf.split(xx2,[1,7], axis=1)
xx2=tf.keras.backend.pool2d(xx2, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')

ss00, xx2= tf.split(xx2,[1,38], axis=1)
xx2=tf.keras.backend.batch_flatten(xx2)
xx2=tf.keras.backend.dot(xx2,tenLb3k1)
# xx2=tf.keras.backend.bias_add(xx2,tenLb)
# xx2=tf.keras.backend.relu(
#     xx2, alpha=0.0, max_value=None, threshold=0
# )

In [64]:
final=tf.keras.backend.bias_add(first+second+third,tenLb3b)
print(final)

tf.Tensor([[-1.5646616  -1.8227314   0.6618474  -0.39152578  0.43304598]], shape=(1, 5), dtype=float32)


In [18]:
ss11==n2

NameError: name 'ss11' is not defined

In [192]:
np.array_equal(final.numpy(),xx.numpy())

False

<tf.Tensor: shape=(1, 2, 5, 8), dtype=float32, numpy=
array([[[[  8.151956  , 219.66093   , 117.35032   , 111.35758   ,
           18.190197  ,   0.        ,   7.9881873 , 136.96495   ],
         [  0.        , 201.476     ,  78.56434   ,  38.03722   ,
          139.52156   ,  31.810286  ,  65.024734  , 217.57787   ],
         [ 41.466637  , 183.81438   ,  89.04685   ,   0.        ,
          241.43266   ,  91.50688   , 168.94705   , 282.62106   ],
         [ 45.22878   , 124.16309   , 109.8422    ,   0.        ,
          174.39491   ,  38.56625   , 164.54234   , 202.43983   ],
         [ 11.727087  , 114.57598   ,  74.539024  ,  22.759573  ,
           32.04222   ,   0.        ,  63.72505   ,  92.3435    ]],

        [[  0.        , 209.66365   , 132.80667   , 111.507996  ,
           43.04256   ,   0.        , 134.0467    , 165.70012   ],
         [ 81.86228   , 268.27774   ,  84.496925  ,   0.93179274,
          306.00067   ,  81.24612   , 190.17996   , 353.69022   ],
         [191

In [158]:
ss11

<tf.Tensor: shape=(1, 3, 5, 8), dtype=float32, numpy=
array([[[[ 36.541428 , 221.65462  , 102.577095 ,  58.684196 ,
           93.43178  ,   0.       , 121.773026 , 175.40202  ],
         [130.84283  , 250.87573  , 178.75114  ,   0.       ,
          301.3193   , 123.903786 , 113.75385  , 352.76404  ],
         [133.61388  , 111.49523  , 139.27148  ,   0.       ,
          183.29822  ,  75.2954   , 175.40135  , 235.22757  ],
         [155.95375  ,  99.241035 , 109.22009  ,   0.       ,
          162.83919  ,  66.05475  , 175.35747  , 215.83873  ],
         [110.40019  ,  49.014683 , 149.8367   ,   0.       ,
          139.97571  ,  38.40401  , 162.15918  , 148.8948   ]],

        [[  0.       , 181.95726  , 101.570244 ,   0.5865016,
           37.77603  ,   0.       , 124.14903  , 125.40097  ],
         [188.9678   , 140.46306  , 155.07541  ,   0.       ,
          248.01918  , 105.55031  , 129.24638  , 332.12863  ],
         [129.99715  , 113.27168  , 114.35794  ,   0.       ,
       

False

True

False