In [160]:
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
print(tf.__version__)

2.3.0


In [196]:
model = tf.keras.models.load_model('con2_300.h5')


In [199]:
for l in model.variables:
    print(l.name)
    if(l.name=="conv2d_6/kernel:0"):
        tenL=l
    if(l.name=="conv2d_6/bias:0"):
        tenLb=l
    if(l.name=="conv2d_7/kernel:0"):
        tenL2=l
    if(l.name=="conv2d_7/bias:0"):
        tenLb2=l
    if(l.name=="dense_2/kernel:0"):
        tenLb3k=l
    if(l.name=="dense_2/bias:0"):
        tenLb3b=l
tenLb3k2, tenLb3k1= tf.split(tenLb3k,[37*75*128,38*75*128], axis=0)

conv2d_6/kernel:0
conv2d_6/bias:0
conv2d_7/kernel:0
conv2d_7/bias:0
dense_2/kernel:0
dense_2/bias:0


In [202]:
import time
sunflower_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/592px-Red_sunflower.jpg"
sunflower_path = tf.keras.utils.get_file('Red_sunflower', origin=sunflower_url)
start_time = time.time()
img = tf.keras.preprocessing.image.load_img(
    sunflower_path , target_size=(300, 300))
img_array = tf.keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) # Create a batch
start_time = time.time()
predictions = model.predict(img_array)
print(predictions)
print("--- %s seconds ---" % (time.time() - start_time))

[[-1.5427666  -1.7926434   0.65167266 -0.3811888   0.42405725]]
--- 0.13699769973754883 seconds ---


In [203]:
c=tf.constant(([0.00392156862745098]))
img_array=tf.math.multiply(
    img_array, c, name=None
)

In [205]:
xx=tf.keras.backend.conv2d(
    img_array, tenL, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)
xx=tf.keras.backend.bias_add(xx, tenLb)
xx=tf.keras.backend.relu(
    xx, alpha=0.0, max_value=None, threshold=0
)
xx=tf.keras.backend.pool2d(xx, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
############################################

xx=tf.keras.backend.conv2d(
    xx, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)
xx=tf.keras.backend.bias_add(xx, tenLb2)
xx=tf.keras.backend.relu(xx, alpha=0.0, max_value=None, threshold=0)
xx=tf.keras.backend.pool2d(xx, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
xx=tf.keras.backend.batch_flatten(xx)
xx=tf.keras.backend.dot(xx,tenLb3k)
xx=tf.keras.backend.bias_add(xx,tenLb3b)

# xx=tf.keras.backend.bias_add(xx, tenLb)
# xx=tf.keras.backend.relu(
#     xx, alpha=0.0, max_value=None, threshold=0
# )
sf0, sf1= tf.split(img_array,[152,148], axis=1)
ss0, ss1= tf.split(img_array,[144,156], axis=1)

In [206]:
xx

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-1.5427666 , -1.7926434 ,  0.65167266, -0.3811888 ,  0.42405725]],
      dtype=float32)>

In [208]:
xx1=tf.keras.backend.conv2d(
    sf0,tenL, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)
xx1=tf.keras.backend.bias_add(xx1, tenLb)
xx1=tf.keras.backend.relu(
    xx1, alpha=0.0, max_value=None, threshold=0
)
xx1=tf.keras.backend.pool2d(xx1, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
#---------------------------------------------------------
xx1=tf.keras.backend.conv2d(
    xx1, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)

xx1=tf.keras.backend.bias_add(xx1, tenLb2)
xx1=tf.keras.backend.relu(xx1, alpha=0.0, max_value=None, threshold=0)
xx1=tf.keras.backend.pool2d(xx1, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')

xx1,sf00= tf.split(xx1,[37,1], axis=1)
xx1=tf.keras.backend.batch_flatten(xx1)
xx1=tf.keras.backend.dot(xx1,tenLb3k2)

# xx1=tf.keras.backend.bias_add(xx1,tenLb)
# xx1=tf.keras.backend.relu(
#     xx1, alpha=0.0, max_value=None, threshold=0
# )
#######################################################################################
xx2=tf.keras.backend.conv2d(
    ss1,tenL, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)
xx2=tf.keras.backend.bias_add(xx2,tenLb)
xx2=tf.keras.backend.relu(
    xx2, alpha=0.0, max_value=None, threshold=0
)
xx2=tf.keras.backend.pool2d(xx2, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
#----------------------------------------------
xx2=tf.keras.backend.conv2d(
    xx2, tenL2, strides=(1, 1), padding='same', data_format=None, dilation_rate=(1,
    1)
)

xx2=tf.keras.backend.bias_add(xx2, tenLb2)
xx2=tf.keras.backend.relu(xx2, alpha=0.0, max_value=None, threshold=0)
#ss00, xx2= tf.split(xx2,[1,7], axis=1)
xx2=tf.keras.backend.pool2d(xx2, pool_size=(2, 2), strides=(2, 2), padding='valid',data_format='channels_last')
ss00, xx2= tf.split(xx2,[1,38], axis=1)
xx2=tf.keras.backend.batch_flatten(xx2)
xx2=tf.keras.backend.dot(xx2,tenLb3k1)
# xx2=tf.keras.backend.bias_add(xx2,tenLb)
# xx2=tf.keras.backend.relu(
#     xx2, alpha=0.0, max_value=None, threshold=0
# )

In [209]:

final=tf.keras.backend.bias_add(xx1+xx2,tenLb3b)
print(final)

tf.Tensor([[-1.5427693  -1.7926426   0.65167224 -0.38118872  0.4240574 ]], shape=(1, 5), dtype=float32)


In [142]:
ss11==n2

In [192]:
np.array_equal(final.numpy(),xx.numpy())

False

<tf.Tensor: shape=(1, 2, 5, 8), dtype=float32, numpy=
array([[[[  8.151956  , 219.66093   , 117.35032   , 111.35758   ,
           18.190197  ,   0.        ,   7.9881873 , 136.96495   ],
         [  0.        , 201.476     ,  78.56434   ,  38.03722   ,
          139.52156   ,  31.810286  ,  65.024734  , 217.57787   ],
         [ 41.466637  , 183.81438   ,  89.04685   ,   0.        ,
          241.43266   ,  91.50688   , 168.94705   , 282.62106   ],
         [ 45.22878   , 124.16309   , 109.8422    ,   0.        ,
          174.39491   ,  38.56625   , 164.54234   , 202.43983   ],
         [ 11.727087  , 114.57598   ,  74.539024  ,  22.759573  ,
           32.04222   ,   0.        ,  63.72505   ,  92.3435    ]],

        [[  0.        , 209.66365   , 132.80667   , 111.507996  ,
           43.04256   ,   0.        , 134.0467    , 165.70012   ],
         [ 81.86228   , 268.27774   ,  84.496925  ,   0.93179274,
          306.00067   ,  81.24612   , 190.17996   , 353.69022   ],
         [191

In [158]:
ss11

<tf.Tensor: shape=(1, 3, 5, 8), dtype=float32, numpy=
array([[[[ 36.541428 , 221.65462  , 102.577095 ,  58.684196 ,
           93.43178  ,   0.       , 121.773026 , 175.40202  ],
         [130.84283  , 250.87573  , 178.75114  ,   0.       ,
          301.3193   , 123.903786 , 113.75385  , 352.76404  ],
         [133.61388  , 111.49523  , 139.27148  ,   0.       ,
          183.29822  ,  75.2954   , 175.40135  , 235.22757  ],
         [155.95375  ,  99.241035 , 109.22009  ,   0.       ,
          162.83919  ,  66.05475  , 175.35747  , 215.83873  ],
         [110.40019  ,  49.014683 , 149.8367   ,   0.       ,
          139.97571  ,  38.40401  , 162.15918  , 148.8948   ]],

        [[  0.       , 181.95726  , 101.570244 ,   0.5865016,
           37.77603  ,   0.       , 124.14903  , 125.40097  ],
         [188.9678   , 140.46306  , 155.07541  ,   0.       ,
          248.01918  , 105.55031  , 129.24638  , 332.12863  ],
         [129.99715  , 113.27168  , 114.35794  ,   0.       ,
       

False

True

False